[project]
name = "commander"
version = "0.0.0"  # Placeholder, override by Git tag
readme = "README.md"
requires-python = ">=3.10"

[tool.poetry.scripts]
commander = "commander.app:main"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
